Update ch01_Strategie.md
Logius-standaarden/BOMOS-Verdieping pull request #14
Opened 2022-12-07 10:50 UTC by edwinwisse

CCvD toegevoegd als een gezamenlijk strategisch overleg.

2023-01-03 12:05 UTC, edwinwisse commented
resolves #12

2023-06-09 07:56 UTC, wisze commented
Uitgaande van de aangeleverde teksten van @erwinfolmer heb ik een appendix toegevoegd met de teksten over edustandaard omdat de teksten te lang zijn om op te nemen in de hoofdtekst.

2023-06-09 08:00 UTC, wisze requested changes

2023-06-09 08:00 UTC, wisze commented on app01_Praktijk.md
> +## Architectuur
Architectuur hoort niet in een document over BOMOS. Het is buiten scope van standaardenbeheer. Ik stel voor deze sectie te verwijderen.

2023-06-09 08:02 UTC, wisze commented on app01_Praktijk.md
> +## Architectuur
Het is een beetje apart dat ik de wijzigingen die ik zelf heb doorgevoerd weer ongedaan wil maken. Het betreft een tekst die ik aangeleverd heb gekregen waarvan ik denk dat deze niet in het document hoort. Het Klankbord mag het zeggen.

2023-06-29 12:03 UTC, edwinwisse reviewed
Reviewed en besproken in klankbord

2023-06-29 12:04 UTC, edwinwisse commented
Besproken in klankbord van 29 juni

2023-06-29 12:04 UTC, merged